NAS_ARR/Controllers/RequestOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.SqlClient;
using System.Net;
using System.Text;
using System.Data;
using System.Globalization;
using Newtonsoft.Json;
using System.Configuration;
using log4net;
using NAS_ARR.Models;
using NAS_ARR.Util;
using System.Threading;

namespace NAS_ARR.Controllers
{
    [BaseController.SessionCheck]
    public class RequestOrderController : BaseController
    {
        #region Variable
            private static readonly ILog logger = LogManager.GetLogger(typeof(RequestOrderController));
            RequestOrderModels _RequestOrderModels = new RequestOrderModels();
            StatusModels _StatusModels = new StatusModels();
            dbNASERequestEntities db = new dbNASERequestEntities();
            Toastr _Toastr = new Toastr();
            string CurrentUser_ID = string.Empty;
        #endregion

        #region GET: Request Order Index Listing Page
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SearchBindOrderStatus()
        {
            var StatusList = GetStatus();
            var modifiedData = StatusList.Select(x => new
            {
                id = x.Code,
                text = x.Description
            });
            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }

        private List<SP_GetAll_Status_Result> GetStatus()
        {
            List<SP_GetAll_Status_Result> _StatusList = new List<SP_GetAll_Status_Result>();
            _StatusList = _StatusModels.GetAllStatus();

            return _StatusList;
        }


        [HttpPost]
        public ActionResult RequestOrderListing()
        {
            JsonResult result = new JsonResult();
            try
            {
                String Search = string.Empty;     
                // Initialization.
                //string search = Request.Form.GetValues("search[value]")[0];
                string draw = Request.Form.GetValues("draw")[0];
                string order = Request.Form.GetValues("order[0][column]")[0];
                string orderDir = Request.Form.GetValues("order[0][dir]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);


                string DateFrom = string.Empty;
                string DateTo = string.Empty;
                String RequestOrder = string.Empty;
                String RequestorName = string.Empty;
                String CategoryFilter = string.Empty;
                String OrderStatus = string.Empty;
                String PaymentStatus = string.Empty;
                String RequestorCodeSearch = string.Empty;

                RequestOrder = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
                //CategoryFilter = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
                OrderStatus = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
                RequestorName = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();
                PaymentStatus = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault();
                DateFrom = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();
                DateTo = Request.Form.GetValues("columns[8][search][value]").FirstOrDefault();                

                int? totalRecords = 0;
                List<SP_Get_RequestOrderList_Result> data = new List<SP_Get_RequestOrderList_Result>();

                if (pageSize == -1)
                    pageSize = Helper.MaximumRows(); //10k

                if (startRec == 0)
                    startRec = 1;

                // Loading.
                //data = _RequestOrderModels.GetRequestOrderList(startRec, pageSize, DateFrom, DateTo, CategoryFilter, OrderStatus,PaymentStatus, RequestorCodeSearch);
                data = _RequestOrderModels.GetRequestOrderList(startRec, pageSize, DateFrom, DateTo, RequestOrder, OrderStatus, RequestorName, PaymentStatus);

                // Total record count.
                if (data.Count > 0)
                {
                    totalRecords = data.FirstOrDefault().TotalCount.Value;
                }

                // Sorting.
                data = this.SortByColumnWithOrder(order, orderDir, data);

                // Filter record count.
                int? recFilter = totalRecords;

                // Apply pagination.
                data = data.Skip(0).Take(pageSize).ToList();

                // Loading drop down lists.                
                result = this.Json(new { draw = Convert.ToInt32(draw), recordsTotal = totalRecords, recordsFiltered = recFilter, data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("RequestOrderListing {0}", ex.Message);
                return HttpNotFound();
            }
            return result;
        }

        private List<SP_Get_RequestOrderList_Result> SortByColumnWithOrder(string order, string orderDir, List<SP_Get_RequestOrderList_Result> data)
        {
            // Initialization.
            List<SP_Get_RequestOrderList_Result> lst = new List<SP_Get_RequestOrderList_Result>();

            try
            {
                // Sorting
                switch (order)
                {
                    case "0":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ID).ToList()
                                                                                                 : data.OrderBy(p => p.ID).ToList();
                        break;

                    case "2":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Request_Code).ToList()
                                                                                                 : data.OrderBy(p => p.Request_Code).ToList();
                        break;

                    case "3":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Description).ToList()
                                                                                                 : data.OrderBy(p => p.Description).ToList();
                        break;

                    case "4":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.I_Status).ToList()
                                                                                                 : data.OrderBy(p => p.I_Status).ToList();
                        break;

                    case "5":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.RequestorName).ToList()
                                                                                                   : data.OrderBy(p => p.RequestorName).ToList();
                        break;
                    case "6":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.PaymentStatus).ToList()
                                                                                                   : data.OrderBy(p => p.PaymentStatus).ToList();
                        break;
                    case "7":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.DeliveryStatus).ToList()
                                                                                                   : data.OrderBy(p => p.DeliveryStatus).ToList();
                        break;
                    case "8":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedOnDate).ToList()
                                                                                                   : data.OrderBy(p => p.CreatedOnDate).ToList();
                        break;
                }
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("SortByColumnWithOrder {0}", ex.Message);
                Console.Write(ex);
            }

            // info.
            return lst;
        }

        //04-10-2018
        //public ActionResult RequestOrderItemList(int? ID,string Category,int? Type)
        //{ 
        //    List<SP_Get_RequestOrderItemList_Result> Get_RequestOrderItemList = new List<SP_Get_RequestOrderItemList_Result>();
        //    if (ID != null && !string.IsNullOrEmpty(Category))
        //    {
        //        Get_RequestOrderItemList = _RequestOrderModels.GetRequestOrderItemList(ID, Category, Type).ToList();
        //    }
        //    return PartialView(Get_RequestOrderItemList);
        //}

        public ActionResult RequestOrderItemList(int? ID, string Category, int? Type,string OrderStatus)
        {
            List<SP_Get_RequestOrderItemList_Result> Get_RequestOrderItemList = new List<SP_Get_RequestOrderItemList_Result>();
            if (ID != null && !string.IsNullOrEmpty(Category))
            {
                Get_RequestOrderItemList = _RequestOrderModels.GetRequestOrderItemList(ID, Category, Type, OrderStatus).ToList();
            }
            return PartialView(Get_RequestOrderItemList);
        }

NAS_ARR/Views/RequestOrder/RequestOrderItemList.cshtml
@model List<SP_Get_RequestOrderItemList_Result>

<table class="table table-responsive table-striped" style="width:97%;padding-top:0px;margin-left:30px;">
    <tr>
        <th style="background-color:#79a0b4;">ITEM</th>
        <th style="background-color:#79a0b4;">UUID</th>
        <th style="background-color:#79a0b4;">ACC NO.</th>
        <th style="background-color:#79a0b4;">RECORD TITLE(FILE NAME)</th>
        <th style="background-color:#79a0b4;">FORMAT</th>
        <th style="background-color:#79a0b4;">RECORD STATUS</th>
        <th style="background-color:#79a0b4;">PAYMENT STATUS</th>
        <th style="background-color:#79a0b4;">DELIVERY STATUS</th>
        <th style="background-color:#79a0b4;">HANDLED BY</th>
        <th style="background-color:#79a0b4;">Last Modified Date</th>
        <th style="background-color:#79a0b4;"></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>            
            <td>@item.Item</td>
            <td>@item.ObjectID</td>
            <td>@item.ObjectDispID</td>            
            <td>@item.RecTitle</td>
            <td>@item.Format</td>
            <td>@item.I_Status</td>
            <td>@item.PaymentStatus</td>
            <td>@item.DeliveryStatus</td>
            <td>@item.ModifiedByUser</td>       
            <td>@item.ModifiedOnDate</td>            
            <td>                
                <a href='@Url.Action("RequestOrderItemEdit", "RequestOrder", new { ID = item.ID, Order_ID = item.Order_ID})'>
                    <span class='fa fa-eye'></span>
                </a>               
            </td>
        </tr>
    }
</table>

NAS_ARR/Views/RequestOrder/_EditMarriageOrderDetail.cshtml
@model NAS_ARR.Models.MarriageRequestOrderViewModels
<div class="modal-header">
    <button id="btnClose" type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Item Details - @Model.Request_Code</h4>(@Model.I_Status)
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("UpdateMarriageStatus", "RequestOrder", FormMethod.Post,
                    new AjaxOptions() { LoadingElementId = "myLoadingElement", OnComplete = "Unloading", OnFailure = "Unloading" },
                    new { id = "formUpdateStatus", @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        <div class="box-body">
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.Item_ID)    
            @Html.HiddenFor(model => model.TS)  
            @Html.HiddenFor(model => model.I_Status)            
            
            <div class="form-group">
                <label for="I_Status" class="col-sm-2 control-label">Update Status :</label>
                <div class="col-sm-4">
                    @Html.DropDownList("Status_Code", (IEnumerable<SelectListItem>)ViewBag.EditStatusList, new { @class = "form-control-sm form-control" })                    
                </div>
                <div class="col-sm-4">
                    <input id="btnUpdateStatus" name="btnUpdateStatus" type="submit" value="Save" class="btn btn-primary btn-flat" />
                    <input id="btnCancel" name="btnCancel" type="submit" value="Close Request" class="btn btn-primary btn-flat" />
                </div>                
            </div>   
            <div class="form-group">
                <label for="ModifiedByUser" class="col-sm-2 control-label">Handle By :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ModifiedByUser, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>          
            <div class="form-group">
                <label for="Unit_Rate" class="col-sm-2 control-label">Item Cost :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.NetAmount, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>
            <div class="form-group">
                <label for="PaymentStatus" class="col-sm-2 control-label">Payment Satus :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.PaymentStatus, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>           
        </div>

        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Items Details</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            @*<div id="toggle-pane-88" class="collapse">*@
            <!-- /.box-header -->
            <div class="box-body" style="">
                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">Item # : </label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.Item, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">Name of Husband :</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.M_NameofHusband, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">Name of Wife :</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.M_NameofWife, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">From Marriage Date :</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.M_From_Date, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">To Marriage Date :</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.M_To_Date, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="I_Status" class="col-sm-2 control-label">Remark :</label>
                        <div class="col-sm-6">
                            @Html.TextBoxFor(m => m.Remark, new { @class = "form-control", @readonly = "true" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="Search_Status_Code" class="col-sm-2 control-label">Search Result :</label>
                        <div class="col-sm-6">
                            @Html.DropDownList("Search_Status_Code", (IEnumerable<SelectListItem>)ViewBag.SearchStatusList, "--Select--", new { @class = "form-control-sm form-control" })
                            @*@Html.DropDownList("Search_Status_Code", new SelectList(Model.EditSearchStatus, "Code", "Description"), "--Select--", new { @class = "form-control" })*@
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label"><label for="FileUpload" class="form-control-label">Upload File :</label></div>
                        <div class="col-sm-6">
                            <input type="file" name="FileUpload" id="FileUpload" class="form-control-file">                            
                        </div>                     
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2 control-label"> 
                            <a href="#" id="button">+Remark</a>                             
                        </div>
                        <div class="col-sm-6">
                            <div id="newpost" style="display:none">                              
                                @Html.TextAreaFor(m => m.CommentDescription, new { @class = "form-control"})
                            </div> 
                        </div>                    
                    </div>
                
            </div>
        </div>
    }    
</div>

<script type="text/javascript">
$(function(){
    $('#button').click(function(){        
        var div = document.getElementById("newpost");        
        if (div.style.display !== "none") {
            div.style.display = "none";
        }
        else {
            div.style.display = "block";
        }      
        return false;
    });
});
</script>

NAS_ARR/Views/RequestOrder/_EditSchoolOrderDetail.cshtml
@model NAS_ARR.Models.SchoolRequestOrderViewModels
<div class="modal-header">
    <button id="btnClose" type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Item Details - @Model.Request_Code</h4>(@Model.I_Status)
</div>
<div class="modal-body">
    @using (Ajax.BeginForm("UpdateSchoolStatus", "RequestOrder", FormMethod.Post,
            new AjaxOptions() { LoadingElementId = "myLoadingElement", OnComplete = "Unloading", OnFailure = "Unloading" },
            new { id = "formUpdateStatus", @class = "form-horizontal", enctype = "multipart/form-data" }))
        {   <!-- /.box-header -->
        <div class="box-body">
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.Item_ID)
            @Html.HiddenFor(model => model.TS)
            @Html.HiddenFor(model => model.I_Status)
            

            <div class="form-group">
                <label for="I_Status" class="col-sm-2 control-label">Update Status :</label>
                <div class="col-sm-6">
                    @Html.DropDownList("Status_Code", (IEnumerable<SelectListItem>)ViewBag.EditStatusList, new { @class = "form-control-sm form-control" })
                    @*@Html.DropDownList("I_Status", new SelectList(Model.EditStatusList, "Code", "Description"), new { @class = "form-control" })*@
                </div>
                <div class="col-sm-4">
                    <input id="btnUpdateStatus" name="btnUpdateStatus" type="submit" value="Save" class="btn btn-primary btn-flat" />
                    <input id="btnCancel" name="btnCancel" type="submit" value="Close Request" class="btn btn-primary btn-flat" />
                </div>
                @*<div class="col-sm-4">
                    <input id="btnUpdateStaus" type="submit" value="Save" class="btn btn-primary btn-flat btn-sm" />
                </div>*@
            </div>
            <div class="form-group">
                <label for="ModifiedByUser" class="col-sm-2 control-label">Handle By :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ModifiedByUser, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>
            <div class="form-group">
                <label for="Unit_Rate" class="col-sm-2 control-label">Item Cost :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.NetAmount, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>
            <div class="form-group">
                <label for="PaymentStatus" class="col-sm-2 control-label">Payment Satus :</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.PaymentStatus, new { @class = "form-control", @readonly = "true" })
                </div>
            </div>
        </div>

        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Items Details</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="">
                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">Item # : </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.Item, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">Name of School :</label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.S_NameOfSchool, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">From Year :</label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.S_From_Year, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">To Year :</label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.S_To_Year, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">Remark :</label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.Remark, new { @class = "form-control", @readonly = "true" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="I_Status" class="col-sm-2 control-label">Search Result :</label>
                    <div class="col-sm-6">
                        @Html.DropDownList("Search_Status_Code", (IEnumerable<SelectListItem>)ViewBag.SearchStatusList, "--Select--", new { @class = "form-control-sm form-control" })
                        @*@Html.DropDownList("I_Status", new SelectList(Model.EditSearchStatus, "Code", "Description"), new { @class = "form-control" })*@
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-2 control-label">
                        <a href="#" id="button">Result Comment</a>
                    </div>
                    <div class="col-sm-6">
                        <div id="newpost" style="display:none">
                            @Html.TextAreaFor(m => m.CommentDescription, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    
</div>


<script type="text/javascript">
$(function(){
    $('#button').click(function(){
        var div = document.getElementById("newpost");
        if (div.style.display !== "none") {
            div.style.display = "none";
        }
        else {
            div.style.display = "block";
        }
        return false;
    });
});
</script>