NAS_ARR/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.SqlClient;
using System.Net;
using System.Text;
using System.Data;
using System.Globalization;
using Newtonsoft.Json;
using System.Configuration;
using log4net;
using NAS_ARR.Models;
using NAS_ARR.Util;

namespace NAS_ARR.Controllers
{
    [BaseController.SessionCheck]
    public class ProductListController : BaseController
    {
        #region Variable
            private static readonly ILog logger = LogManager.GetLogger(typeof(ProductListController));
            Price_RuleModels _Price_RuleModels = new Price_RuleModels();
            CategoryModels _CategoryModels = new CategoryModels();
            dbNASERequestEntities db = new dbNASERequestEntities();
            Toastr _Toastr = new Toastr();
            string CurrentUser_ID = string.Empty;
        #endregion
        
        #region GET: ProductList
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SearchBindCategory()
        {
            var CounrtyList = GetCategory();
            var modifiedData = CounrtyList.Select(x => new
            {
                id = x.Code,
                text = x.Description
            });
            return Json(modifiedData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ProductListing()
        {
            JsonResult result = new JsonResult();
            try
            {
                // Initialization.
                //string search = Request.Form.GetValues("search[value]")[0];
                string draw = Request.Form.GetValues("draw")[0];
                string order = Request.Form.GetValues("order[0][column]")[0];
                string orderDir = Request.Form.GetValues("order[0][dir]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);
                

                string DateFrom = string.Empty;
                string DateTo = string.Empty;
                String CategoryFilter = string.Empty;
                String Search = string.Empty;

                CategoryFilter = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();

                DateFrom = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();
                DateTo = Request.Form.GetValues("columns[8][search][value]").FirstOrDefault();
                Search = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();

                

                int? totalRecords = 0;
                List<SP_Get_ProductList_Result> data = new List<SP_Get_ProductList_Result>();

                if (pageSize == -1)
                    pageSize = Helper.MaximumRows(); //10k

                if (startRec == 0)
                    startRec = 1;

                // Loading.
                data = _Price_RuleModels.GetProductList(startRec, pageSize, DateFrom, DateTo, CategoryFilter, Search);

                // Total record count.
                if (data.Count > 0)
                {
                    totalRecords = data.FirstOrDefault().TotalCount.Value;
                }

                // Sorting.
                data = this.SortByColumnWithOrder(order, orderDir, data);

                // Filter record count.
                int? recFilter = totalRecords;

                // Apply pagination.
                data = data.Skip(0).Take(pageSize).ToList();

                // Loading drop down lists.                
                result = this.Json(new { draw = Convert.ToInt32(draw), recordsTotal = totalRecords, recordsFiltered = recFilter, data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("ProductListing {0}", ex.Message);
                return HttpNotFound();
            }
            return result;
        }

        private List<SP_Get_ProductList_Result> SortByColumnWithOrder(string order, string orderDir, List<SP_Get_ProductList_Result> data)
        {
            // Initialization.
            List<SP_Get_ProductList_Result> lst = new List<SP_Get_ProductList_Result>();

            try
            {
                // Sorting
                switch (order)
                {
                    case "0":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ID).ToList()
                                                                                                 : data.OrderBy(p => p.ID).ToList();
                        break;

                    case "1":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Category_Code).ToList()
                                                                                                 : data.OrderBy(p => p.Category_Code).ToList();
                        break;

                    case "2":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Rule_Name).ToList()
                                                                                                 : data.OrderBy(p => p.Rule_Name).ToList();
                        break;

                    case "3":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Format).ToList()
                                                                                                 : data.OrderBy(p => p.Format).ToList();
                        break;

                    case "4":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Unit_Rate).ToList()
                                                                                                   : data.OrderBy(p => p.Unit_Rate).ToList();
                        break;

                    case "5":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Status).ToList()
                                                                                                 : data.OrderBy(p => p.Status).ToList();
                        break;
                    case "6":
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedByUserID).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedByUserID).ToList();
                        break;
                    default:
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedOnDate).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedOnDate).ToList();
                        break;
                }
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("SortByColumnWithOrder {0}", ex.Message);
                Console.Write(ex);
            }

            // info.
            return lst;
        }
        #endregion

        #region NEW : Product        
        public ActionResult AddNewProductList()
        {
            try
            {
                PriceRuleViewModel _PriceRuleViewModel = new PriceRuleViewModel();
                BindControl();             
                return View("AddNew", _PriceRuleViewModel);
            }
            catch (Exception ex)
            {
                logger.ErrorFormat("AddNewProductList {0}", ex.Message);
                return HttpNotFound();
            }
        }

        [HttpPost]        
        public ActionResult SaveProductInfo(PriceRuleViewModel Price_RuleData)
        {
            string Message = string.Empty;                    
            try
            {
                if (ModelState.IsValid)
                {
                    if (Price_RuleData != null)
                    {
                        Message = CheckValidData(Price_RuleData);
                        if (Message == string.Empty)
                        {
                            Price_Rule _Price_Rule = new Price_Rule();
                            _Price_Rule.Category_Code = Price_RuleData.Category_Code;
                            _Price_Rule.Rule_Name = Price_RuleData.Rule_Name;
                            _Price_Rule.Format = Price_RuleData.Format;
                            _Price_Rule.UOM = Price_RuleData.UOM;
                            _Price_Rule.Unit_Per_Set = Price_RuleData.Unit_Per_Set;
                            _Price_Rule.Unit_Rate = Price_RuleData.Unit_Rate;
                            _Price_Rule.FullOrPatial = Price_RuleData.FullOrPatial;
                            _Price_Rule.CreatedByUserID = Price_RuleData.CreatedByUserID;
                            Message = _Price_RuleModels.InsertProductPriceRule(_Price_Rule);

                            if (Message != string.Empty)
                            {
                                ModelState.AddModelError(string.Empty, Message);
                            }
                        }else
                        {
                            ModelState.AddModelError(string.Empty, Message);
                        }                
                    }
                    else

NAS_ARR/Views/ProductList/AddNew.cshtml
@model NAS_ARR.Models.PriceRuleViewModel
@{
    ViewBag.Title = "AddNew";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Add New Product Details
        </h1>       
    </div>
    <div class="content-header clearfix">
        <div class="pull-left">
            <i class="fa fa-arrow-circle-left"></i>
            <a href="/ARR_Admin/ProductList/Index">back to listing</a>
        </div>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-md-12">
                    @*<h4>General Information</h4>*@ 
                            @using (Ajax.BeginForm("SaveProductInfo", "ProductList", FormMethod.Post,
                            new AjaxOptions() { LoadingElementId = "myLoadingElement", OnComplete = "Unloading", OnFailure = "Unloading" },
                            new { id = "formAddProduct", @class = "form-horizontal", enctype = "multipart/form-data" }))                           
                           {
                                    @*@Html.Partial("ValidationSummary", ViewData.ModelState)*@
                                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                    @Html.AntiForgeryToken()

                                    <div class="form-group">
                                        <label for="ddlCategory" class="col-sm-2 control-label">Product Category :</label>
                                        <div class="col-sm-6">
                                            @Html.DropDownList("Category_Code", new SelectList(ViewBag.CategoryTemplte, "Code", "Description"), new { @class = "form-control-sm form-control" })
                                        </div>
                                     </div>


                                    <div class="form-group">
                                        <label for="txtRule_Name" class="col-sm-2 control-label">Product Name :</label>
                                        <div class="col-sm-6">
                                            @Html.TextBoxFor(m => m.Rule_Name, new { @class = "form-control", @required = true })                                          
                                        </div>
                                    </div>

                                    <div class="form-group">
                                            <label for="txtFormat" class="col-sm-2 control-label">Format :</label>
                                            <div class="col-sm-6">
                                                @Html.TextBoxFor(m => m.Format, new { @class = "form-control", @required = true })                                                
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="txtUOM" class="col-sm-2 control-label">Unit of Measure :</label>
                                            <div class="col-sm-6">
                                                @Html.TextBoxFor(m => m.UOM, new { @class = "form-control", @required = true })                                                
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="txtUnit_Per_Set" class="col-sm-2 control-label">Unit Per Set :</label>
                                            <div class="col-sm-6">
                                                @Html.TextBoxFor(m => m.Unit_Per_Set, new { @class = "form-control", @required = true })
                                              
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="txtUnit_Rate" class="col-sm-2 control-label">Unit Rate($) *:</label>
                                            <div class="col-sm-6">
                                                @{var formated = String.Format("{0:0.00}", Model.Unit_Rate);}
                                                @Html.TextBoxFor(m => m.Unit_Rate, formated, new { @class = "form-control", @required = true })                                                
                                            </div>
                                        </div>

                                        if (ViewBag.FullOrPatialTemplate != null)
                                        {
                                            <div id="divFullOrPatialTemplate" class="row form-group">
                                                <label for="rdoFullorPatial" class="col-sm-2 control-label"></label>
                                                <div class="col-12 col-md-8">
                                                    @foreach (SelectListItem itemdata in ViewBag.FullOrPatialTemplate)
                                                    {
                                                        @Html.RadioButton("FullOrPatial", @itemdata.Value, itemdata.Selected, new { id = @itemdata.Value })
                                                        @Html.Label(@itemdata.Text)
                                                    }
                                                </div>
                                            </div>
                                        }

                                        <div class="form-group">
                                            <label class="col-sm-2 control-label"></label>
                                            <div class="col-sm-6">
                                                <input id="btnProductSaved" type="submit" value="Save" class="btn btn-primary btn-flat" />
                                                <a href="/ProductList/Index" class="btn  btn-default btn-flat">Cancel</a>
                                            </div>
                                        </div>
                              }
                     </div>                    
                <!-- nav-tabs-custom -->
            </div>
        </div>
</div>



<script>
    $('#Category_Code').change(function () {
        var ctype = $("#Category_Code").val();
        var x = document.getElementById("divFullOrPatialTemplate");        
        if (ctype == 'AV' || ctype == 'OH')
        {
          $('input').iCheck('uncheck');
          x.style.display = "block";
        }else
        {
            x.style.display = "none";       
            $('input').iCheck('uncheck');
        }
    });
</script>

NAS_ARR/Views/ProductList/Detail.cshtml
@model NAS_ARR.Models.PriceRuleViewModel
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Edit Product Details
        </h1>
        @*<div class="pull-right">           
            <a class="btn bg-green" href="/Admin/Category/ExportXml">
                <i class="fa fa-file-code-o"></i>
                Export to XML
            </a>
        </div>*@
    </div>
    <div class="content-header clearfix">
        <div class="pull-left">
            <i class="fa fa-arrow-circle-left"></i>
            <a href="/ProductList/Index">back to listing</a>
        </div>
    </div>

    <div class="content">        
        <div class="row">
            <div class="col-md-12">
                <!-- Custom Tabs -->
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab_1" data-toggle="tab">Info</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_1">
                            <h4>General Information</h4>
                            <div class="box box-info">   
                                @using (Ajax.BeginForm("UpdateProductInfo", "ProductList", FormMethod.Post,
                            new AjaxOptions() { LoadingElementId = "myLoadingElement", OnComplete = "Unloading", OnFailure = "Unloading" },
                            new { id = "form-ProductList", @class = "form-horizontal", enctype = "multipart/form-data" }))
                                {
                                    @Html.HiddenFor(model => model.ID)
                                    @Html.HiddenFor(model => model.Category_Code)                                    
                                    <!-- /.box-header -->
                                    <div class="box-body"> 
                                            <div class="form-group">
                                                <label for="txtProductID" class="col-sm-2 control-label">Order Status :</label>
                                                <div class="col-sm-6">                                                    
                                                    @Html.TextBoxFor(m => m.Status, new { @class = "form-control", @readonly = "true" })
                                                </div>
                                             </div>

                                            <div class="form-group">
                                                <label for="txtCategoryDescription"  class="col-sm-2 control-label">Request ID :</label>
                                                <div class="col-sm-6">                                                    
                                                    @Html.TextBoxFor(m => m.CategoryDescription, new { @class = "form-control", @readonly = "true" })
                                                </div>
                                                </div>

                                            <div class="form-group">
                                                <label for="txtRule_Name" class="col-sm-2 control-label">Product Name :</label>
                                                <div class="col-sm-6">                                                  
                                                    @Html.TextBoxFor(m => m.Rule_Name, new { @class = "form-control", @readonly = "true" })                                                                                                        
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label for="txtFormat"  class="col-sm-2 control-label">Format :</label>
                                                <div class="col-sm-6">                                                                                                                                                         
                                                    @Html.TextBoxFor(m => m.Format, new { @class = "form-control", @readonly = "true" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label for="txtUOM"  class="col-sm-2 control-label">Unit of Measure :</label>
                                                <div class="col-sm-6">
                                                    @Html.TextBoxFor(m => m.UOM, new { @class = "form-control", @required = true})                                                    
                                                    @*@Html.TextBoxFor(m => m.UOM, new { id = "txtUOM", @class = "form-control" })*@
                                                </div>
                                            </div>    

                                            <div class="form-group">
                                                <label for="txtUnit_Per_Set" class="col-sm-2 control-label">Unit Per Set :</label>
                                                <div class="col-sm-6">
                                                    @Html.TextBoxFor(m => m.Unit_Per_Set, new { @class = "form-control", @required = true })                                                                                                        
                                                </div>
                                            </div>    

                                            <div class="form-group">
                                                <label for="txtUnit_Rate" class="col-sm-2 control-label">Unit Rate($) *:</label>
                                                <div class="col-sm-6">
                                                    @Html.TextBoxFor(m => m.Unit_Rate, new { @class = "form-control", @required = true })
                                                   
                                                </div>
                                                @if (Model.Category_Code == "AV" || Model.Category_Code == "OH")
                                                {
                                                    if (Model.FullOrPatial == 1)
                                                    {
                                                        <label>Full Price</label>
                                                    }
                                                    else if (Model.FullOrPatial == 2)
                                                    {
                                                        <label>Patial Price</label>
                                                    }
                                                }
                                            </div>                                           

                                            @*<div class="form-group">
                                                <label for="txtCreatedOnDate" class="col-sm-2 control-label">Created Date :</label>
                                                <div class="col-sm-6">                                                    
                                                    @Html.TextBoxFor(m => m.CreatedOnDate, new { @class = "form-control"})
                                                </div>
                                            </div>*@     

                                            <div class="form-group">
                                                <label for="txtCreatedByUserID" class="col-sm-2 control-label">Created By :</label>
                                                <div class="col-sm-6">                                                    
                                                    @Html.TextBoxFor(m => m.CreatedByUserID, new { @class = "form-control", @readonly = "true" })
                                                </div>
                                            </div>   
                                        
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"></label>
                                                <div class="col-sm-6">                                                    
                                                    <input id="btnProductUpdate" type="submit" value="Update" class="btn btn-primary btn-flat" />
                                                    <a href="/ProductList/Index" class="btn  btn-default btn-flat">Cancel</a>
                                                </div>
                                            </div>                     
                                    </div>
                                }
                            </div>            
                        </div>                       
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- nav-tabs-custom -->
            </div>
        </div>
    </div>
</div>