NAS_ARR/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.SqlClient;
using System.Net;
using System.Text;
using System.Data;
using System.Globalization;
using Newtonsoft.Json;
using System.Configuration;
using log4net;
using NAS_ARR.Models;
using NAS_ARR.Util;

namespace NAS_ARR.Controllers
{
    [BaseController.SessionCheck]
    public class LanguageController : BaseController
    {
        #region Variable
        private static readonly ILog logger = LogManager.GetLogger(typeof(LanguageController));
        LanguageModels _LanguageModels = new LanguageModels();
        dbNASERequestEntities db = new dbNASERequestEntities();
        Toastr _Toastr = new Toastr();

        int? CurrentUser_ID = 0;
        #endregion

        #region GET Language
        public ActionResult Index()
        {
            return View("LanguageView");
        }

        public ActionResult LanguageView()
        {
            JsonResult result = new JsonResult();
            try
            {
                // Initialization.
                string search = Request.Form.GetValues("search[value]")[0];
                string draw = Request.Form.GetValues("draw")[0];
                string order = Request.Form.GetValues("order[0][column]")[0];
                string orderDir = Request.Form.GetValues("order[0][dir]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);
                int? totalRecords = 0;
                List<sp_Get_Language_Result> data = new List<sp_Get_Language_Result>();
                if (pageSize == -1)
                    pageSize = Helper.MaximumRows(); //10k

                if (startRec == 0)
                    startRec = 1;

                // Loading.
                data = _LanguageModels.GetLanguageMain(startRec, pageSize, search);

                // Total record count.
                if (data.Count > 0)
                {
                    totalRecords = data.FirstOrDefault().TotalCount.Value;
                }
            
                // Sorting.
                data = this.SortByColumnWithOrder(order, orderDir, data);

                // Filter record count.
                int? recFilter = totalRecords;

                // Apply pagination.
                data = data.Skip(0).Take(pageSize).ToList();

                // Loading drop down lists.
                result = this.Json(new { draw = Convert.ToInt32(draw), recordsTotal = totalRecords, recordsFiltered = recFilter, data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return HttpNotFound();
            }
            return result;
        }

        private List<sp_Get_Language_Result> SortByColumnWithOrder(string order, string orderDir, List<sp_Get_Language_Result> data)
        {
            // Initialization.
            List<sp_Get_Language_Result> lst = new List<sp_Get_Language_Result>();

            try
            {
                // Sorting
                switch (order)
                {
                    case "0":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.Name).ToList()
                                                                                                 : data.OrderBy(p => p.Name).ToList();
                        break;

                    case "1":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedByUserName).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedByUserName).ToList();
                        break;

                    case "2":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedOnDate).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedOnDate).ToList();
                        break;
                    default:
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ID).ToList()
                                                                                                 : data.OrderBy(p => p.ID).ToList();
                        break;
                }
            }
            catch (Exception ex)
            {
                // info.
                Console.Write(ex);
            }

            // info.
            return lst;
        }
        #endregion

        #region Get Language Item

        public ActionResult LanguageEditView(int? ID)
        {
            ViewBag.Language_ID = ID;
            return View("LanguageEditView");
        }

        public ActionResult ViewLanguageItemList(int? ID)
        {
            JsonResult result = new JsonResult();
            try
            {
                // Initialization.
                string search = Request.Form.GetValues("search[value]")[0];
                string draw = Request.Form.GetValues("draw")[0];
                string order = Request.Form.GetValues("order[0][column]")[0];
                string orderDir = Request.Form.GetValues("order[0][dir]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);
                int? totalRecords = 0;
                List<SP_Get_LanguageItem_Result> data = new List<SP_Get_LanguageItem_Result>();
                if (pageSize == -1)
                    pageSize = Helper.MaximumRows(); //10k

                if (startRec == 0)
                    startRec = 1;

                // Loading.
                data = _LanguageModels.GetLanguageItem(ID,startRec, pageSize, search);

                // Total record count.
                if (data.Count > 0)
                {
                    totalRecords = data.FirstOrDefault().TotalCount.Value;
                }

                // Sorting.
                data = this.Item_SortByColumnWithOrder(order, orderDir, data);

                // Filter record count.
                int? recFilter = totalRecords;

                // Apply pagination.
                data = data.Skip(0).Take(pageSize).ToList();

                // Loading drop down lists.
                result = this.Json(new { draw = Convert.ToInt32(draw), recordsTotal = totalRecords, recordsFiltered = recFilter, data = data }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return HttpNotFound();
            }
            return result;
        }


        private List<SP_Get_LanguageItem_Result> Item_SortByColumnWithOrder(string order, string orderDir, List<SP_Get_LanguageItem_Result> data)
        {
            // Initialization.
            List<SP_Get_LanguageItem_Result> lst = new List<SP_Get_LanguageItem_Result>();

            try
            {
                // Sorting
                switch (order)
                {
                    case "1":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ResourceName).ToList()
                                                                                                 : data.OrderBy(p => p.ResourceName).ToList();
                        break;

                    case "2":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ResourceValue).ToList()
                                                                                                 : data.OrderBy(p => p.ResourceValue).ToList();
                        break;

                    case "3":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedByUserName).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedByUserName).ToList();
                        break;
                    case "4":
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.CreatedOnDate).ToList()
                                                                                                 : data.OrderBy(p => p.CreatedOnDate).ToList();
                        break;
                    default:
                        // Setting.
                        lst = orderDir.Equals("DESC", StringComparison.CurrentCultureIgnoreCase) ? data.OrderByDescending(p => p.ID).ToList()
                                                                                                 : data.OrderBy(p => p.ID).ToList();
                        break;
                }
            }
            catch (Exception ex)
            {
                // info.
                Console.Write(ex);
            }

            // info.
            return lst;
        }        
        #endregion
    }
}

NAS_ARR/Views/Language/LanguageEditView.cshtml
@model List<SP_Get_LanguageItem_Result>
@{
    ViewBag.Title = "LanguageEditView";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int _ID = ViewBag.Language_ID;
}


<div class="content-wrapper">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Edit language Details 
        </h1>
    </div>

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                <!--AdvanceSearch-->
                <div class="panel panel-default panel-search">
                    <div class="panel-body" style="padding-bottom:0px !important;padding-top:0px !important">
                        <div class="box box-solid collapsed-box" style="box-shadow:none;margin-bottom:0px">
                            <div class="box-header ui-sortable-handle" data-widget="collapse">
                                <i class="fa fa-search"></i>
                                <h3 class="box-title">Search</h3>
                            </div>
                            <div class="box-body border-radius-none" style="">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="col-md-4">
                                                <div gd class="label-wrapper">
                                                    <label class="control-label" for="txtName">Resource Name</label>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <input class="form-control text-box single-line" id="txtRName" name="txtRName" value="" type="text">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="col-md-4">
                                                <div gd class="label-wrapper">
                                                    <label class="control-label" for="txtName">Value</label>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <input class="form-control text-box single-line" id="txtValue" name="txtValue" value="" type="text">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-7 col-md-offset-5">
                                        <div class="pull-right">
                                            <button type="button" id="btnsearchlanguage" class="btn btn-primary btn-search">
                                                <i class="fa fa-search"></i>
                                                Search
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Listing-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div id="customers-grid" data-role="grid">
                            <table class="table table-striped table-bordered table-hover" id="TableId" cellspacing="0" align="center" width="100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Resource Name</th>
                                        <th>Value</th>
                                        <th>Created User</th>
                                        <th>Created Date</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="EditModal" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="ModalTitle">EDIT PAGE</h4>                
            </div>
            <div class="modal-body">
                @using (Ajax.BeginForm("UpdateLanguateItem", "Language", FormMethod.Post,
                 new AjaxOptions() { LoadingElementId = "myLoadingElement", OnComplete = "Unloading", OnFailure = "Unloading" },
                 new { id = "form-Edit", @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        <input type="hidden" name="hE_ID" id="hE_ID">
                        <div class="row form-group">
                            <div class="col col-md-3"><label for="lblResource" class="form-control-label">Resource Name</label></div>
                            <div class="col-12 col-md-9">
                                <input type="text" id="txtResource" name="txtResource" value="" class="form-control" required="true"/>                                
                            </div>
                        </div>                      
                     
                        <div class="row form-group">
                            <div class="col col-md-3"><label for="txtValues" class="form-control-label">Values</label></div>
                            <div class="col-12 col-md-9"><input type="text" id="txtValues" name="txtValues" value="" class="form-control" required=true /></div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button id="btnUpdateLanguage" type="submit" value="Update" name="btnUpdate" class="btn bg-blue">
                            <i class="fa fa-floppy-o"></i>
                            Update
                        </button>                        
                        <a href="javascript:void(0);" class="btn btn-primary btn-sm Custombtn" data-dismiss="modal" id="btnEbookcanel">Cancel</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">
    var Language_ID = '@(ViewBag.Language_ID)';
    $(document).ready(function () {
        var oTable = $('#TableId').DataTable(
        {
            "lengthMenu": [[500, 1000, 1500, -1], [500, 1000, 1500, "All"]],
            "columnDefs": [
                { "width": "5%", "targets": 0 },
                { "width": "30%", "targets": 1 },
                { "width": "30%", "targets": 2 },
                { "width": "20%", "targets": 3 },
                { "width": "20%", "targets": 4 },
                { "width": "5%", "targets": 5 },
                { "width": "5%", "targets": 6 },
                { "className": "custom-middle-align", "targets": [0, 1, 2, 3, 4, 5, 6] },
                { orderable: false, targets: [5,6] }
            ],
            "language":
                {
                    "processing": "<div class='overlay custom-loader-background'><i class='fa fa-cog fa-spin custom-loader-color'></i></div>"
                },
            "processing": true,
            "serverSide": true,
            "ajax":
                {
                    "url": "/Language/ViewLanguageItemList/" + Language_ID,
                    "type": "POST",
                    "dataType": "JSON"
                },
            "columns": [
                        { "data": "Name" },
                        { "data": "ResourceName" },
                        { "data": "ResourceValue" },
                        { "data": "CreatedByUserName" },
                        {
                            "data": "CreatedOnDate"
                            ,"render": function (data) { return convertToDate(data); }
                        },
                        {
                            "data": "ID",
                            "mRender": function (data, type, full) {
                                return '<a class="btn btn-default"  href="javascript:void(0);" onclick="EditRecord(' + data + ')"><i class="fa fa-edit"></i></a>';
                            }
                        },
                         {
                             "data": "ID",
                             "mRender": function (data, type, full) {
                                 return '<a class="btn btn-default"  href="javascript:void(0);" onclick="DeleteRecord(' + data + ')"><i class="fa fa-trash-o"></i></a>';                                 
                             }
                         },
                ]
        });
    });


    function EditRecord(ID) {
        //$('#hE_ID').val(ID);    
        alert(ID);
        jQuery('#EditModal').modal();
        //var url = "/OOTD/EditOOTDByID?ID=" + ID;
        var url = "";
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                //var obj = JSON.parse(JSON.stringify(data));
                //var SetData = $("#UlAttList");
                //$('#txtimage').remove();
                //$("#txtLocation").val(obj.Location);
                //var Data = "<li id='txtimage'>" +
                //        "<a class='title' href='" + obj.Frames_Patch + "' target='blank'>" +
                //        "<img src='" + obj.Frames_Patch + "' alt='' height='120px' width='150px'/>" + obj.Frames_Name + "" +
                //        "</a>"
                //"</li>";
                //SetData.append(Data);
            }
        })
    }
</script>

NAS_ARR/Views/Language/LanguageView.cshtml
@{
    ViewBag.Title = "LanguageView";
    Layout = "~/Views/Shared/_Layout.cshtml";  
}

<div class="content-wrapper">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            Language
        </h1>    
    </div>

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">    
                <!--Listing-->
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div id="customers-grid" data-role="grid">
                            <table class="table table-striped table-bordered table-hover" id="TableId" cellspacing="0" align="center" width="100%">
                                <thead>
                                    <tr>
                                        <th>Language</th>
                                        <th>Created User</th>
                                        <th>Created Date</th>                                      
                                        <th>View Detail</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        var oTable = $('#TableId').DataTable(
        {
            "lengthMenu": [[100, 200, 300, -1], [100, 200, 300, "All"]],            
            "order": [[0, "desc"]],
            "columnDefs": [
                { "width": "15%", "targets": [3] },                
                { orderable: false, targets: [1] }
            ],
            "language":
                {
                    "processing": "<div class='overlay custom-loader-background'><i class='fa fa-cog fa-spin custom-loader-color'></i></div>"
                },
            "processing": true,
            "serverSide": true,
            "ajax":
                {
                    "url": "/Language/LanguageView",
                    "type": "POST",
                    "dataType": "JSON"
                },
            "columns": [
                        { "data": "Name" },
                        { "data": "CreatedByUserName" },                        
                        {
                            "data": "CreatedOnDate"
                            ,"render": function (data) { return convertToDate(data); }
                        },                                            
                        {
                            "data": "ID",
                            "mRender": function (data, type, full) {
                                return '<a href=/Language/LanguageEditView/' + data + '>' + 'View Detail</a>';
                        }},
                ]
        });    
    });
</script>